import { starterPrompt, type StarterPromptDefinition } from "./helpers";

/** Real estate listing, buyer, and investor tools. */
export const REAL_ESTATE_PROMPTS: StarterPromptDefinition[] = [
  starterPrompt(
    "Listing Description Writer",
    "real-estate",
    ["Listing", "Copy", "MLS"],
    2.99,
    "intermediate",
    "45 minutes",
    "real estate copywriter",
    "write an MLS-ready listing description that highlights features and neighborhood appeal",
    [
      "Headline options (3)",
      "Full listing description",
      "Feature bullet list",
      "Neighborhood lifestyle paragraph",
      "Social media teaser",
    ],
  ),
  starterPrompt(
    "Buyer Consultation Script",
    "real-estate",
    ["Buyers", "Consultation", "Scripts"],
    2.99,
    "intermediate",
    "1 hour",
    "buyer's agent coach",
    "structure a buyer consultation that qualifies needs and earns the representation agreement",
    [
      "Rapport and expectations setting",
      "Needs assessment questions",
      "Financing pre-qual talking points",
      "Buyer agreement close script",
      "Follow-up email template",
    ],
  ),
  starterPrompt(
    "Open House Follow-Up Sequence",
    "real-estate",
    ["Open House", "Follow-Up", "Leads"],
    1.99,
    "beginner",
    "30 minutes",
    "real estate ISA",
    "write follow-up texts and emails for open house attendees",
    [
      "Same-day thank-you text",
      "Next-day value email",
      "3-day showing invite",
      "7-day check-in",
    ],
  ),
  starterPrompt(
    "CMA Presentation Outline",
    "real-estate",
    ["CMA", "Pricing", "Sellers"],
    2.99,
    "intermediate",
    "90 minutes",
    "listing agent trainer",
    "build a comparative market analysis presentation for a seller appointment",
    [
      "Pricing strategy narrative",
      "Comp summary talking points",
      "Net proceeds estimate framework",
      "Marketing plan overview",
      "Listing agreement close",
    ],
  ),
  starterPrompt(
    "Rental Property ROI Analyzer",
    "real-estate",
    ["Rental", "ROI", "Investing"],
    2.99,
    "intermediate",
    "1 hour",
    "real estate investment analyst",
    "analyze a rental property's cash flow, cap rate, and ROI from user inputs",
    [
      "Monthly cash flow breakdown",
      "Cap rate and cash-on-cash return",
      "Expense assumptions",
      "Sensitivity scenarios",
      "Go / no-go recommendation",
    ],
  ),
  starterPrompt(
    "Neighborhood Market Report",
    "real-estate",
    ["Market Report", "Data", "Buyers"],
    2.99,
    "intermediate",
    "1 hour",
    "local market analyst",
    "write a buyer-friendly neighborhood market snapshot",
    [
      "Median price and trend summary",
      "Inventory and days-on-market",
      "Schools and amenities highlights",
      "Best-fit buyer profile",
      "Shareable email version",
    ],
  ),
  starterPrompt(
    "Offer Strategy Playbook",
    "real-estate",
    ["Offers", "Negotiation", "Buyers"],
    2.99,
    "advanced",
    "1 hour",
    "real estate negotiator",
    "recommend offer terms and negotiation strategy for a specific property",
    [
      "Offer price rationale",
      "Contingency recommendations",
      "Escalation or appraisal gap options",
      "Seller motivation angles",
      "Counteroffer response scripts",
    ],
  ),
  starterPrompt(
    "Staging Checklist Generator",
    "real-estate",
    ["Staging", "Listing", "Sellers"],
    1.99,
    "beginner",
    "30 minutes",
    "home staging consultant",
    "create a room-by-room staging checklist to maximize listing appeal",
    [
      "Curb appeal tasks",
      "Room-by-room staging list",
      "Depersonalization tips",
      "Quick-win budget fixes",
      "Photo-day prep timeline",
    ],
  ),
  starterPrompt(
    "Property Showing Script",
    "real-estate",
    ["Showing", "Buyers", "Scripts"],
    1.99,
    "beginner",
    "20 minutes",
    "showing coach for agents",
    "script a property showing tour that highlights features and gauges buyer interest",
    [
      "Arrival and disclosure opener",
      "Room-by-room talk track",
      "Objection handlers",
      "Closing questions and next steps",
    ],
  ),
  starterPrompt(
    "Lease Review Guide",
    "real-estate",
    ["Lease", "Rentals", "Tenants"],
    1.99,
    "intermediate",
    "45 minutes",
    "residential leasing specialist",
    "summarize lease terms and flag items for a tenant or landlord to review",
    [
      "Key terms plain-English summary",
      "Red flags checklist",
      "Negotiation points to request",
      "Move-in documentation list",
    ],
    "Educational only — not legal advice.",
  ),
  starterPrompt(
    "Real Estate Social Post Pack",
    "real-estate",
    ["Social Media", "Marketing", "Listings"],
    2.99,
    "beginner",
    "45 minutes",
    "real estate social media marketer",
    "write a week of social posts for a new listing or agent brand",
    [
      "Just listed post",
      "Feature spotlight carousel outline",
      "Neighborhood highlight post",
      "Client testimonial prompt",
      "Open house promo",
    ],
  ),
  starterPrompt(
    "Investor Deal Analyzer",
    "real-estate",
    ["Investing", "Flip", "Analysis"],
    2.99,
    "advanced",
    "2 hours",
    "real estate investment advisor",
    "analyze a fix-and-flip or BRRRR deal with profit projections",
    [
      "ARV and rehab estimate validation",
      "All-in cost breakdown",
      "Profit and margin scenarios",
      "Timeline and risk factors",
      "Proceed / renegotiate / pass recommendation",
    ],
  ),
];
