import { starterPrompt, type StarterPromptDefinition } from "./helpers";

/** PromptBase-style bestsellers: outreach, discovery, proposals, objections, closing. */
export const SALES_PROMPTS: StarterPromptDefinition[] = [
  starterPrompt(
    "Cold Email Sequence Generator",
    "sales",
    ["Cold Email", "Outreach", "B2B"],
    2.99,
    "intermediate",
    "2 hours",
    "B2B sales development rep",
    "write a 4-email cold outreach sequence for the user's ICP, offer, and proof points",
    [
      "Email 1: pattern-interrupt opener under 80 words",
      "Email 2: value-add follow-up with case study angle",
      "Email 3: social proof + specific CTA",
      "Email 4: breakup email with door-open close",
      "Subject line options for each email",
    ],
  ),
  starterPrompt(
    "Discovery Call Question Bank",
    "sales",
    ["Discovery", "Qualification", "Calls"],
    2.99,
    "intermediate",
    "1 hour",
    "enterprise sales coach",
    "build a discovery call script with questions that uncover pain, budget, authority, and timeline",
    [
      "Opening rapport (2 min)",
      "Situation questions (5)",
      "Problem questions (5)",
      "Implication questions (3)",
      "Need-payoff questions (3)",
      "Next-step close script",
    ],
  ),
  starterPrompt(
    "Sales Proposal Writer",
    "sales",
    ["Proposal", "Closing", "B2B"],
    2.99,
    "intermediate",
    "90 minutes",
    "B2B proposal specialist",
    "draft a client-ready sales proposal from discovery notes and scope inputs",
    [
      "Executive summary",
      "Problem statement and goals",
      "Proposed solution and deliverables",
      "Timeline and milestones",
      "Investment options (good/better/best)",
      "Terms and next steps",
    ],
  ),
  starterPrompt(
    "Objection Handler Playbook",
    "sales",
    ["Objections", "Closing", "Scripts"],
    1.99,
    "beginner",
    "45 minutes",
    "sales trainer",
    "address the user's top 8 sales objections with empathetic responses and proof points",
    [
      "Objection → acknowledge → reframe → proof for each",
      "One-liner cheat sheet",
      "When to walk away signals",
    ],
  ),
  starterPrompt(
    "CRM Lead Scoring Assistant",
    "sales",
    ["CRM", "Leads", "Qualification"],
    2.99,
    "intermediate",
    "1 hour",
    "revenue operations analyst",
    "score and prioritize leads from the user's CRM export or lead list",
    [
      "Scoring rubric (fit, intent, engagement)",
      "Tier A/B/C lead lists",
      "Recommended next actions per tier",
      "Disqualification flags",
    ],
  ),
  starterPrompt(
    "LinkedIn Sales DM Writer",
    "sales",
    ["LinkedIn", "Outreach", "Social Selling"],
    1.99,
    "beginner",
    "30 minutes",
    "LinkedIn social selling specialist",
    "write personalized LinkedIn connection and follow-up DMs that book meetings",
    [
      "Connection request note (300 chars)",
      "Post-connect message",
      "Value-share follow-up",
      "Meeting ask message",
    ],
  ),
  starterPrompt(
    "Follow-Up Email Sequence",
    "sales",
    ["Follow-Up", "Email", "Pipeline"],
    1.99,
    "beginner",
    "45 minutes",
    "sales copywriter",
    "create a post-demo or post-meeting follow-up email sequence",
    [
      "Same-day recap email",
      "48-hour value-add follow-up",
      "7-day urgency nudge",
      "14-day final check-in",
    ],
  ),
  starterPrompt(
    "Sales Pitch Deck Outline",
    "sales",
    ["Pitch", "Deck", "Presentation"],
    2.99,
    "intermediate",
    "2 hours",
    "startup pitch coach",
    "structure a 10-slide sales pitch deck for the user's product and buyer persona",
    [
      "Slide-by-slide headlines and bullet content",
      "Speaker notes per slide",
      "Demo transition script",
      "Q&A prep for top 5 objections",
    ],
  ),
  starterPrompt(
    "BANT Qualification Script",
    "sales",
    ["BANT", "Qualification", "SDR"],
    1.99,
    "beginner",
    "20 minutes",
    "SDR team lead",
    "qualify inbound or outbound leads using BANT with natural conversational flow",
    [
      "Budget questions",
      "Authority mapping",
      "Need discovery",
      "Timeline urgency",
      "Qualify / nurture / disqualify recommendation",
    ],
  ),
  starterPrompt(
    "Negotiation Prep Worksheet",
    "sales",
    ["Negotiation", "Deals", "Closing"],
    2.99,
    "advanced",
    "1 hour",
    "enterprise deal strategist",
    "prepare for a sales negotiation with BATNA, anchors, and concession strategy",
    [
      "Walk-away point and BATNA",
      "Buyer priorities hypothesis",
      "Concession ladder",
      "Trade-off options",
      "Closing language",
    ],
  ),
  starterPrompt(
    "Demo Script Builder",
    "sales",
    ["Demo", "SaaS", "Presentation"],
    2.99,
    "intermediate",
    "90 minutes",
    "SaaS sales engineer",
    "write a 30-minute product demo script tailored to the buyer's use case",
    [
      "Agenda and success criteria",
      "Discovery recap hook",
      "Feature walkthrough tied to pain points",
      "Proof point moments",
      "Trial / next-step close",
    ],
  ),
  starterPrompt(
    "Prospect Research Brief",
    "sales",
    ["Research", "Prospecting", "Account"],
    1.99,
    "beginner",
    "30 minutes",
    "account intelligence researcher",
    "compile a pre-call research brief on a target account and contact",
    [
      "Company snapshot and recent news",
      "Likely pain points",
      "Stakeholder map",
      "Personalization hooks for outreach",
      "Competitive landscape notes",
    ],
  ),
  starterPrompt(
    "Closing Email Templates",
    "sales",
    ["Closing", "Email", "Templates"],
    1.99,
    "beginner",
    "30 minutes",
    "sales enablement writer",
    "draft closing emails for different deal stages and buyer hesitation types",
    [
      "Assumptive close email",
      "Summary close email",
      "Urgency close email",
      "Final offer email",
    ],
  ),
  starterPrompt(
    "Account Expansion Playbook",
    "sales",
    ["Expansion", "Upsell", "Account"],
    2.99,
    "intermediate",
    "1 hour",
    "customer success sales leader",
    "identify upsell and cross-sell opportunities within an existing account",
    [
      "Usage and satisfaction signals",
      "Expansion triggers",
      "Stakeholder outreach plan",
      "Business case outline",
      "Expansion pitch email",
    ],
  ),
  starterPrompt(
    "Win-Loss Analysis Framework",
    "sales",
    ["Analysis", "Pipeline", "Strategy"],
    2.99,
    "intermediate",
    "1 hour",
    "sales operations manager",
    "analyze won and lost deals to extract patterns and process improvements",
    [
      "Win themes and repeatable tactics",
      "Loss reasons by category",
      "Competitive insights",
      "Process fixes (top 5)",
      "Coaching recommendations",
    ],
  ),
  starterPrompt(
    "Sales Meeting Agenda Generator",
    "sales",
    ["Meetings", "Agenda", "Productivity"],
    1.99,
    "beginner",
    "15 minutes",
    "sales productivity coach",
    "create a tight agenda for a sales meeting with clear outcomes",
    [
      "Pre-read materials",
      "Timed agenda blocks",
      "Decision items",
      "Action owners and deadlines",
    ],
  ),
  starterPrompt(
    "Territory Planning Assistant",
    "sales",
    ["Territory", "Planning", "Quota"],
    2.99,
    "advanced",
    "2 hours",
    "regional sales director",
    "build a territory plan that hits quota with account prioritization",
    [
      "Account segmentation (TAM/SAM)",
      "Tier 1/2/3 account lists",
      "Weekly activity targets",
      "Quarterly milestone plan",
    ],
  ),
  starterPrompt(
    "Contract Review Checklist",
    "sales",
    ["Contract", "Legal", "Closing"],
    1.99,
    "intermediate",
    "45 minutes",
    "sales operations specialist",
    "review a sales contract or order form for red flags before sending to legal",
    [
      "Commercial terms checklist",
      "Risk flags to escalate",
      "Standard fallback language suggestions",
      "Approval routing recommendation",
    ],
    "Educational only — not legal advice.",
  ),
  starterPrompt(
    "Sales Enablement One-Pager",
    "sales",
    ["Enablement", "Collateral", "Messaging"],
    2.99,
    "intermediate",
    "1 hour",
    "sales enablement manager",
    "create a one-page sales sheet with messaging, proof, and talk tracks",
    [
      "Value proposition headline",
      "3 key benefits with proof points",
      "Ideal customer profile",
      "Competitive differentiation",
      "CTA and objection handlers",
    ],
  ),
  starterPrompt(
    "Voicemail Script Generator",
    "sales",
    ["Voicemail", "Cold Call", "SDR"],
    1.99,
    "beginner",
    "15 minutes",
    "inside sales coach",
    "write voicemail scripts for cold outreach that get callbacks",
    [
      "15-second hook voicemail",
      "30-second value voicemail",
      "Referral-request voicemail",
      "Follow-up voicemail after email",
    ],
  ),
];
