import { starterPrompt, type StarterPromptDefinition } from "./helpers";

export const SCRUBBING_PROMPTS: StarterPromptDefinition[] = [
  starterPrompt(
    "Twitter/X Tweet Scrubbing Audit",
    "marketing",
    ["Twitter", "X", "Audit", "Reputation"],
    2.99,
    "intermediate",
    "2 hours",
    "social media reputation consultant specializing in Twitter/X",
    "audit the user's Twitter/X timeline for brand risk, outdated opinions, and content that could harm their career or business",
    [
      "Risk tier summary (high / medium / low) with tweet count estimates",
      "Category breakdown: political, controversial, unprofessional, outdated, personal oversharing",
      "Top 10 highest-risk tweets to review or delete first",
      "Platform-specific cleanup priorities and timeline",
      "Brand-safe posting guidelines going forward",
    ],
    "Ask the user to paste recent tweets, describe their industry/role, and note any past controversies. Be direct about reputational risk without being alarmist.",
  ),
  starterPrompt(
    "Delete Risky Old Tweets Checklist",
    "productivity",
    ["Twitter", "Cleanup", "Checklist", "Delete"],
    2.99,
    "beginner",
    "1 hour",
    "digital hygiene coach focused on social media cleanup",
    "create a prioritized checklist for finding and deleting risky old tweets",
    [
      "Pre-deletion backup steps (archive download, screenshot log)",
      "Search queries and keywords to hunt for risky content by category",
      "Priority order: delete first vs. rewrite vs. leave",
      "Batch deletion workflow with safety checkpoints",
      "Post-cleanup verification checklist",
    ],
  ),
  starterPrompt(
    "LinkedIn Profile Cleanup",
    "marketing",
    ["LinkedIn", "Profile", "Professional", "Cleanup"],
    2.99,
    "beginner",
    "45 minutes",
    "LinkedIn personal branding specialist",
    "review and optimize the user's LinkedIn profile for professional credibility and remove brand risk",
    [
      "Headline rewrite options (3 variants)",
      "About section improvements with tone alignment",
      "Experience bullets cleaned for ATS and recruiter appeal",
      "Content audit: posts and comments that should be edited or removed",
      "Profile photo and banner recommendations",
    ],
  ),
  starterPrompt(
    "Instagram Brand Risk Review",
    "marketing",
    ["Instagram", "Brand", "Audit", "Visual"],
    2.99,
    "intermediate",
    "1 hour",
    "Instagram brand strategist and reputation analyst",
    "review the user's Instagram presence for brand inconsistencies, risky content, and reputation gaps",
    [
      "Bio and link-in-bio optimization suggestions",
      "Grid aesthetic and content theme assessment",
      "Highlights and Stories archive risk flags",
      "Caption tone audit with rewrite suggestions for flagged posts",
      "Hashtag and tagged-content cleanup recommendations",
    ],
  ),
  starterPrompt(
    "Facebook Post Audit",
    "marketing",
    ["Facebook", "Audit", "Privacy", "Cleanup"],
    2.99,
    "beginner",
    "45 minutes",
    "Facebook privacy and reputation consultant",
    "audit the user's Facebook history for privacy leaks, outdated posts, and content that could damage their reputation",
    [
      "Privacy settings checklist (who can see what)",
      "Post categories to search and review (photos, tags, comments, groups)",
      "Timeline cleanup priority list by decade/year",
      "Friend and tag management recommendations",
      "Future posting and tagging guardrails",
    ],
  ),
  starterPrompt(
    "Social Media Reputation Cleanup",
    "productivity",
    ["Reputation", "Cleanup", "Multi-Platform", "Crisis"],
    2.99,
    "intermediate",
    "2 hours",
    "cross-platform reputation management advisor",
    "design a comprehensive social media cleanup plan across all platforms the user mentions",
    [
      "Platform-by-platform audit summary and risk scores",
      "Unified cleanup timeline (week 1, 2, 3 actions)",
      "Content to delete, archive, or rewrite on each platform",
      "Google search result mitigation tips (SEO basics for personal brand)",
      "Ongoing monitoring routine (weekly/monthly)",
    ],
  ),
  starterPrompt(
    "Pre-Job-Interview Social Scrub",
    "productivity",
    ["Job Search", "Interview", "LinkedIn", "Twitter"],
    2.99,
    "beginner",
    "30 minutes",
    "career coach specializing in employer background checks and social screening",
    "prepare the user's social profiles for recruiter and employer review before job interviews",
    [
      "Recruiter-first impression audit (LinkedIn, Twitter/X, Instagram)",
      "Red-flag content checklist specific to hiring managers",
      "48-hour rapid cleanup action plan",
      "Google-your-name simulation: what employers might find",
      "Safe topics to post about during an active job search",
    ],
  ),
  starterPrompt(
    "Controversial Tweet Finder",
    "marketing",
    ["Twitter", "Controversy", "Search", "Audit"],
    2.99,
    "intermediate",
    "1 hour",
    "social media forensic analyst",
    "help the user identify potentially controversial tweets using keyword patterns, topic categories, and context clues",
    [
      "Custom keyword and phrase search list tailored to user's industry",
      "Topic categories to scan: politics, religion, hot takes, employer complaints, jokes that aged poorly",
      "Scoring rubric for controversy severity (1–5)",
      "Sample search workflow for Twitter advanced search",
      "Decision matrix: delete vs. context-add vs. ignore",
    ],
  ),
  starterPrompt(
    "Brand-Safe Tweet Rewriter",
    "marketing",
    ["Twitter", "Rewrite", "Brand Safety", "Copywriting"],
    2.99,
    "beginner",
    "30 minutes",
    "brand-safe social copywriter",
    "rewrite flagged tweets to preserve the user's voice while removing reputational risk",
    [
      "Original vs. rewritten version for each flagged tweet",
      "Explanation of what was changed and why",
      "Tone calibration options (professional, witty-safe, neutral)",
      "Alternative phrasings when deletion isn't needed",
      "Guidelines for similar posts in the future",
    ],
  ),
  starterPrompt(
    "Social Media Crisis Response Planner",
    "marketing",
    ["Crisis", "PR", "Response", "Reputation"],
    2.99,
    "advanced",
    "2 hours",
    "crisis communications strategist for social media incidents",
    "create a response plan when old posts resurface or a social media controversy is brewing",
    [
      "Situation assessment and severity level",
      "Immediate actions (24-hour playbook)",
      "Hold statement and public apology templates if needed",
      "Stakeholder communication order (employer, clients, audience)",
      "Long-term reputation recovery steps",
    ],
    "This is for planning and drafting only — not legal advice. Recommend legal counsel for serious situations.",
  ),
];
