import { starterPrompt, type StarterPromptDefinition } from "./helpers";

/** PromptBase-style social & content tools. */
export const SOCIAL_MEDIA_PROMPTS: StarterPromptDefinition[] = [
  starterPrompt(
    "Instagram Caption Writer",
    "social-media",
    ["Instagram", "Captions", "Content"],
    1.99,
    "beginner",
    "20 minutes",
    "Instagram content strategist",
    "write scroll-stopping captions for the user's post idea, brand voice, and audience",
    [
      "3 caption variants (short, medium, long)",
      "Hashtag set (15–20)",
      "CTA options",
      "First-comment strategy",
    ],
  ),
  starterPrompt(
    "TikTok Hook Generator",
    "social-media",
    ["TikTok", "Hooks", "Video"],
    1.99,
    "beginner",
    "15 minutes",
    "short-form video strategist",
    "generate 10 TikTok/Reels hooks that stop the scroll in the first 2 seconds",
    [
      "Hook scripts with visual cues",
      "Pattern labels (curiosity, contrarian, story)",
      "Suggested on-screen text",
      "CTA for each hook",
    ],
  ),
  starterPrompt(
    "Social Content Calendar",
    "social-media",
    ["Calendar", "Planning", "Content"],
    2.99,
    "intermediate",
    "1 hour",
    "social media manager",
    "build a 30-day content calendar across the user's platforms and pillars",
    [
      "4 content pillars",
      "30-day post schedule table",
      "Format mix (carousel, reel, static)",
      "Batching workflow tips",
    ],
  ),
  starterPrompt(
    "Hashtag Strategy Builder",
    "social-media",
    ["Hashtags", "Discovery", "Instagram"],
    1.99,
    "beginner",
    "20 minutes",
    "social growth specialist",
    "research and organize hashtags for reach and niche targeting",
    [
      "Broad, niche, and branded hashtag tiers",
      "30 hashtags grouped by post type",
      "Banned or low-quality tags to avoid",
      "Rotation strategy",
    ],
  ),
  starterPrompt(
    "Influencer Outreach DM",
    "social-media",
    ["Influencer", "Outreach", "Partnerships"],
    2.99,
    "intermediate",
    "45 minutes",
    "influencer marketing manager",
    "write outreach DMs and emails to creators for brand partnerships",
    [
      "Initial DM (short)",
      "Follow-up message",
      "Brief outline to attach",
      "Negotiation talking points",
    ],
  ),
  starterPrompt(
    "Reels Script Writer",
    "social-media",
    ["Reels", "Script", "Video"],
    1.99,
    "beginner",
    "30 minutes",
    "video content producer",
    "script a 30–60 second Reel or TikTok with hook, body, and CTA",
    [
      "Hook (0–3 sec)",
      "Beat-by-beat script",
      "B-roll suggestions",
      "Caption and hashtags",
    ],
  ),
  starterPrompt(
    "Social Bio Optimizer",
    "social-media",
    ["Bio", "Profile", "Branding"],
    1.99,
    "beginner",
    "15 minutes",
    "personal branding coach",
    "rewrite social bios for clarity, credibility, and conversion",
    [
      "3 bio options per platform",
      "Link-in-bio CTA suggestion",
      "Keyword optimization notes",
      "Pinned post recommendations",
    ],
  ),
  starterPrompt(
    "Engagement Reply Templates",
    "social-media",
    ["Engagement", "Community", "Comments"],
    1.99,
    "beginner",
    "20 minutes",
    "community manager",
    "create on-brand reply templates for comments and DMs",
    [
      "Positive comment replies (5)",
      "Question responses (5)",
      "Complaint de-escalation (3)",
      "DM FAQ responses (5)",
    ],
  ),
  starterPrompt(
    "Carousel Post Planner",
    "social-media",
    ["Carousel", "Instagram", "Design"],
    2.99,
    "intermediate",
    "45 minutes",
    "carousel content designer",
    "outline a high-save Instagram carousel slide by slide",
    [
      "Cover slide headline",
      "8–10 slide titles and bullet copy",
      "CTA slide",
      "Design notes per slide",
    ],
  ),
  starterPrompt(
    "YouTube Title & Thumbnail Brief",
    "social-media",
    ["YouTube", "SEO", "Video"],
    2.99,
    "intermediate",
    "45 minutes",
    "YouTube growth strategist",
    "generate click-worthy titles and thumbnail concepts for a video topic",
    [
      "10 title options with CTR rationale",
      "3 thumbnail concepts (text + visual)",
      "Description SEO keywords",
      "Pinned comment suggestion",
    ],
  ),
  starterPrompt(
    "Social Audit Checklist",
    "social-media",
    ["Audit", "Brand", "Strategy"],
    2.99,
    "intermediate",
    "1 hour",
    "social media consultant",
    "audit the user's social profiles and content for brand consistency and growth blockers",
    [
      "Profile optimization scorecard",
      "Content pillar gaps",
      "Posting frequency analysis",
      "30-day improvement plan",
    ],
  ),
  starterPrompt(
    "UGC Campaign Brief",
    "social-media",
    ["UGC", "Campaign", "Creators"],
    2.99,
    "intermediate",
    "1 hour",
    "UGC campaign manager",
    "write a creator brief for a user-generated content campaign",
    [
      "Campaign objective and KPIs",
      "Creative dos and don'ts",
      "Shot list and examples",
      "Usage rights summary",
      "Submission checklist",
    ],
  ),
  starterPrompt(
    "Trendjacking Post Generator",
    "social-media",
    ["Trends", "News", "Content"],
    1.99,
    "beginner",
    "20 minutes",
    "real-time social editor",
    "turn a trending topic into on-brand social posts without forcing it",
    [
      "3 post angles (safe, bold, educational)",
      "Risk assessment per angle",
      "Recommended platform per post",
    ],
  ),
  starterPrompt(
    "Pinterest Pin Description Writer",
    "social-media",
    ["Pinterest", "SEO", "E-commerce"],
    1.99,
    "beginner",
    "20 minutes",
    "Pinterest SEO specialist",
    "write SEO-optimized pin titles and descriptions that drive clicks",
    [
      "5 pin title options",
      "Description with keywords",
      "Board placement strategy",
      "Seasonal refresh tips",
    ],
  ),
  starterPrompt(
    "Social Crisis Response Planner",
    "social-media",
    ["Crisis", "PR", "Reputation"],
    2.99,
    "advanced",
    "1 hour",
    "social crisis communications lead",
    "draft a response plan for negative social media attention",
    [
      "Severity assessment",
      "Hold statement options",
      "Response timeline (first hour, 24h)",
      "Internal escalation checklist",
      "Recovery content ideas",
    ],
  ),
];
