import { starterPrompt, type StarterPromptDefinition } from "./helpers";

export const STARTER_PROMPTS: StarterPromptDefinition[] = [
  // ── Productivity (20) ──────────────────────────────────────────────
  starterPrompt(
    "Daily Prioritizer",
    "productivity",
    ["Planning", "Priorities", "Daily"],
    1.99,
    "beginner",
    "30 minutes",
    "productivity coach specializing in daily planning",
    "turn the user's task list, deadlines, and energy level into a prioritized daily plan",
    [
      "Top 3 must-do tasks with time estimates",
      "Secondary tasks grouped by context (deep work, admin, calls)",
      "Suggested time blocks with breaks",
      "One-sentence focus mantra for the day",
    ],
  ),
  starterPrompt(
    "Weekly Planner",
    "productivity",
    ["Weekly", "Planning", "Schedule"],
    1.99,
    "beginner",
    "45 minutes",
    "executive assistant skilled in weekly planning",
    "create a balanced weekly plan from the user's goals, commitments, and deadlines",
    [
      "Day-by-day schedule with major blocks",
      "Theme days or focus areas (e.g., deep work Monday)",
      "Buffer time for overflow and unexpected tasks",
      "Weekly review checklist for Friday",
    ],
  ),
  starterPrompt(
    "Eisenhower Matrix Assistant",
    "productivity",
    ["Eisenhower", "Prioritization", "Matrix"],
    1.99,
    "beginner",
    "20 minutes",
    "productivity consultant",
    "sort the user's tasks into Urgent/Important quadrants and recommend actions",
    [
      "Quadrant 1 (Do Now) tasks with deadlines",
      "Quadrant 2 (Schedule) tasks with suggested dates",
      "Quadrant 3 (Delegate) tasks with delegation notes",
      "Quadrant 4 (Eliminate) tasks with rationale",
    ],
  ),
  starterPrompt(
    "Focus Session Planner",
    "productivity",
    ["Focus", "Deep Work", "Pomodoro"],
    1.99,
    "beginner",
    "15 minutes",
    "deep work coach",
    "design a focused work session for the user's most important task",
    [
      "Pre-session setup checklist (environment, notifications, materials)",
      "25–90 minute session structure with micro-breaks",
      "Distraction capture method for intrusive thoughts",
      "Post-session review prompts",
    ],
  ),
  starterPrompt(
    "Goal Breakdown Architect",
    "productivity",
    ["Goals", "Milestones", "OKRs"],
    2.99,
    "intermediate",
    "1 hour",
    "goal-setting strategist",
    "break a large goal into milestones, weekly actions, and measurable outcomes",
    [
      "SMART goal statement refined from user input",
      "3–5 major milestones with target dates",
      "Weekly action items for the next 4 weeks",
      "Success metrics and review cadence",
    ],
  ),
  starterPrompt(
    "Habit Stack Designer",
    "productivity",
    ["Habits", "Behavior", "Routine"],
    1.99,
    "beginner",
    "30 minutes",
    "behavior change coach",
    "design habit stacks that attach new behaviors to existing routines",
    [
      "Anchor habit identification from user's current routine",
      "3 habit stacks with trigger → action → reward",
      "Implementation intentions (if-then plans)",
      "14-day tracking template",
    ],
  ),
  starterPrompt(
    "Morning Routine Optimizer",
    "productivity",
    ["Morning", "Routine", "Energy"],
    1.99,
    "beginner",
    "20 minutes",
    "morning routine specialist",
    "optimize the user's morning routine for energy, clarity, and momentum",
    [
      "Ideal wake time and first-hour timeline",
      "Activities ranked by impact (movement, nutrition, planning, learning)",
      "Minimal viable routine for busy days",
      "Evening prep steps to support the morning",
    ],
  ),
  starterPrompt(
    "Evening Shutdown Ritual",
    "productivity",
    ["Evening", "Wind Down", "Closure"],
    1.99,
    "beginner",
    "15 minutes",
    "productivity coach focused on work-life boundaries",
    "create an evening shutdown ritual that closes open loops and prepares for tomorrow",
    [
      "5-step shutdown checklist (inbox, calendar, priorities, workspace, reflection)",
      "Brain dump template for lingering thoughts",
      "Tomorrow's top 3 preview",
      "Boundary phrase or ritual to signal end of work",
    ],
  ),
  starterPrompt(
    "Task Delegation Planner",
    "productivity",
    ["Delegation", "Team", "Management"],
    2.99,
    "intermediate",
    "45 minutes",
    "operations manager",
    "identify tasks to delegate and create clear delegation briefs",
    [
      "Tasks categorized: keep, delegate, automate, eliminate",
      "Delegation brief for each task (outcome, context, deadline, authority level)",
      "Suggested assignee criteria if no person named",
      "Follow-up check-in schedule",
    ],
  ),
  starterPrompt(
    "Deep Work Schedule Builder",
    "productivity",
    ["Deep Work", "Calendar", "Focus"],
    2.99,
    "intermediate",
    "1 hour",
    "Cal Newport-style deep work consultant",
    "build a weekly deep work schedule protected from meetings and shallow work",
    [
      "Audit of current calendar with shallow vs. deep work ratio",
      "Recommended deep work blocks (days, times, duration)",
      "Meeting batching strategy",
      "Communication boundaries to protect focus time",
    ],
  ),
  starterPrompt(
    "Inbox Zero Assistant",
    "productivity",
    ["Email", "Inbox", "Triage"],
    1.99,
    "beginner",
    "30 minutes",
    "email productivity expert",
    "triage the user's inbox and create filters, templates, and a processing workflow",
    [
      "Email categories and folder/label structure",
      "Quick-reply templates for common messages",
      "Filter rules for automated sorting",
      "Daily 15-minute inbox processing routine",
    ],
  ),
  starterPrompt(
    "Calendar Audit Optimizer",
    "productivity",
    ["Calendar", "Meetings", "Time Audit"],
    2.99,
    "intermediate",
    "45 minutes",
    "executive time management consultant",
    "audit the user's calendar and recommend cuts, consolidations, and boundaries",
    [
      "Meeting inventory with time cost per week",
      "Meetings to cancel, shorten, or make async",
      "Ideal calendar template for next week",
      "Scripts for declining or rescheduling meetings",
    ],
  ),
  starterPrompt(
    "Energy Management Coach",
    "productivity",
    ["Energy", "Ultradian", "Performance"],
    2.99,
    "intermediate",
    "30 minutes",
    "performance psychologist",
    "map the user's energy patterns and align high-value work with peak hours",
    [
      "Energy map (peak, moderate, low periods)",
      "Task types matched to energy levels",
      "Recovery rituals for low-energy periods",
      "Weekly rhythm recommendations",
    ],
  ),
  starterPrompt(
    "Procrastination Breakthrough",
    "productivity",
    ["Procrastination", "Motivation", "Action"],
    1.99,
    "beginner",
    "20 minutes",
    "behavioral coach specializing in procrastination",
    "diagnose why the user is procrastinating and create a micro-action plan to start",
    [
      "Root cause analysis (fear, ambiguity, overwhelm, boredom)",
      "2-minute starter action for the avoided task",
      "Environment and accountability tweaks",
      "Reward system for completion milestones",
    ],
  ),
  starterPrompt(
    "Second Brain Setup",
    "productivity",
    ["PKM", "Notes", "Knowledge Management"],
    2.99,
    "advanced",
    "2 hours",
    "personal knowledge management architect",
    "design a second brain system for capturing, organizing, and retrieving information",
    [
      "Capture workflow (inbox, quick capture tools)",
      "Folder/tag structure or PARA method setup",
      "Weekly review process",
      "3 starter templates (meeting notes, project, reference)",
    ],
  ),
  starterPrompt(
    "Personal OKR Writer",
    "productivity",
    ["OKRs", "Quarterly", "Goals"],
    2.99,
    "intermediate",
    "1 hour",
    "OKR coach for individuals",
    "write personal OKRs for the quarter with key results and check-in cadence",
    [
      "1–3 objectives aligned to user's stated priorities",
      "2–4 measurable key results per objective",
      "Initiatives mapped to each key result",
      "Monthly and weekly check-in questions",
    ],
  ),
  starterPrompt(
    "Time Audit Analyzer",
    "productivity",
    ["Time Audit", "Tracking", "Analysis"],
    2.99,
    "intermediate",
    "45 minutes",
    "time management analyst",
    "analyze how the user spends time and recommend reallocations",
    [
      "Time log analysis by category (work, admin, learning, rest)",
      "Hours per week on high-value vs. low-value activities",
      "Top 3 time leaks with fix recommendations",
      "Ideal time budget for next week",
    ],
  ),
  starterPrompt(
    "Batch Processing Planner",
    "productivity",
    ["Batching", "Efficiency", "Workflow"],
    1.99,
    "beginner",
    "20 minutes",
    "workflow optimization specialist",
    "group similar tasks into batches to reduce context switching",
    [
      "Task inventory grouped by type (email, calls, content, admin)",
      "Recommended batch days and time blocks",
      "Batch size and frequency guidelines",
      "Tools or templates to support each batch",
    ],
  ),
  starterPrompt(
    "Decision Fatigue Reducer",
    "productivity",
    ["Decisions", "Routines", "Automation"],
    1.99,
    "beginner",
    "15 minutes",
    "decision-making coach",
    "identify recurring decisions and create defaults, rules, or checklists",
    [
      "List of daily/weekly recurring decisions",
      "Default choices or decision rules for each",
      "Checklists to eliminate re-deciding",
      "One decision to delegate or automate this week",
    ],
  ),
  starterPrompt(
    "Quarterly Life Review",
    "productivity",
    ["Review", "Reflection", "Quarterly"],
    2.99,
    "intermediate",
    "1.5 hours",
    "life design coach",
    "facilitate a quarterly life review across career, health, relationships, and growth",
    [
      "Reflection prompts for each life area",
      "Wins, lessons, and disappointments summary",
      "Priority shifts for next quarter",
      "3 commitments with deadlines",
    ],
  ),

  // ── Business (20) ──────────────────────────────────────────────────
  starterPrompt(
    "One-Page Business Plan",
    "business",
    ["Business Plan", "Startup", "Strategy"],
    1.99,
    "beginner",
    "45 minutes",
    "startup advisor",
    "condense the user's business idea into a one-page business plan",
    [
      "Problem, solution, and unique value proposition",
      "Target customer and market size estimate",
      "Revenue model and pricing approach",
      "90-day action plan with milestones",
    ],
  ),
  starterPrompt(
    "SWOT Analysis Builder",
    "business",
    ["SWOT", "Strategy", "Analysis"],
    1.99,
    "beginner",
    "30 minutes",
    "business strategist",
    "conduct a SWOT analysis for the user's business or project",
    [
      "Strengths (internal, positive)",
      "Weaknesses (internal, negative)",
      "Opportunities (external, positive)",
      "Threats (external, negative) with strategic actions for each quadrant",
    ],
  ),
  starterPrompt(
    "Meeting Agenda Creator",
    "business",
    ["Meetings", "Agenda", "Facilitation"],
    1.99,
    "beginner",
    "15 minutes",
    "executive assistant",
    "create a structured meeting agenda with objectives, topics, and time allocations",
    [
      "Meeting objective and desired outcomes",
      "Agenda items with owner and time limit",
      "Pre-read materials list",
      "Action item capture template",
    ],
  ),
  starterPrompt(
    "Meeting Notes Summarizer",
    "business",
    ["Meetings", "Summary", "Action Items"],
    1.99,
    "beginner",
    "20 minutes",
    "executive assistant",
    "summarize messy meeting notes into decisions, action items, and follow-ups",
    [
      "Executive summary (3–5 bullets)",
      "Key decisions made",
      "Action items table: owner | task | deadline",
      "Draft follow-up email to attendees",
    ],
  ),
  starterPrompt(
    "Cold Outreach Email Writer",
    "business",
    ["Cold Email", "Outreach", "B2B"],
    2.99,
    "intermediate",
    "30 minutes",
    "B2B sales development representative",
    "write personalized cold outreach emails based on prospect research",
    [
      "Subject line variants (3 options)",
      "Email body under 150 words with personalization hook",
      "Clear CTA (meeting, reply, resource)",
      "Follow-up email for 3 and 7 days later",
    ],
  ),
  starterPrompt(
    "Client Proposal Generator",
    "business",
    ["Proposal", "Clients", "Freelance"],
    2.99,
    "intermediate",
    "1 hour",
    "freelance business consultant",
    "generate a client proposal with scope, timeline, deliverables, and pricing",
    [
      "Executive summary and understanding of client needs",
      "Scope of work with deliverables",
      "Timeline with milestones",
      "Pricing options (good/better/best if applicable)",
    ],
  ),
  starterPrompt(
    "SOP Writer",
    "business",
    ["SOP", "Process", "Operations"],
    2.99,
    "intermediate",
    "45 minutes",
    "operations consultant",
    "write a standard operating procedure for a business process",
    [
      "Purpose and scope of the SOP",
      "Step-by-step instructions with owners",
      "Required tools and resources",
      "Quality checkpoints and exception handling",
    ],
  ),
  starterPrompt(
    "KPI Dashboard Planner",
    "business",
    ["KPIs", "Metrics", "Dashboard"],
    2.99,
    "intermediate",
    "45 minutes",
    "business analyst",
    "define KPIs and a dashboard structure for the user's business or team",
    [
      "5–8 KPIs with definitions and formulas",
      "Target values and review frequency",
      "Data sources for each metric",
      "Dashboard layout recommendation",
    ],
  ),
  starterPrompt(
    "Competitive Analysis Brief",
    "business",
    ["Competitive Analysis", "Market", "Strategy"],
    2.99,
    "intermediate",
    "1 hour",
    "competitive intelligence analyst",
    "analyze competitors and recommend positioning strategies",
    [
      "Competitor profiles (features, pricing, positioning, strengths/weaknesses)",
      "Comparison matrix",
      "Differentiation opportunities",
      "Recommended messaging angles",
    ],
  ),
  starterPrompt(
    "Pricing Strategy Advisor",
    "business",
    ["Pricing", "Revenue", "Strategy"],
    2.99,
    "intermediate",
    "45 minutes",
    "pricing strategist",
    "recommend pricing tiers, packaging, and value metrics for the user's offer",
    [
      "Pricing model recommendation (subscription, one-time, usage-based)",
      "2–3 tier structure with features and price points",
      "Value metric justification",
      "Pricing experiments to run in the next 30 days",
    ],
  ),
  starterPrompt(
    "Job Description Writer",
    "business",
    ["Hiring", "Job Description", "HR"],
    1.99,
    "beginner",
    "20 minutes",
    "talent acquisition specialist",
    "write an inclusive, compelling job description for an open role",
    [
      "Role summary and team context",
      "Responsibilities (must-have vs. nice-to-have)",
      "Qualifications and experience requirements",
      "Benefits, culture highlights, and application instructions",
    ],
  ),
  starterPrompt(
    "Interview Question Generator",
    "business",
    ["Interview", "Hiring", "Questions"],
    1.99,
    "beginner",
    "30 minutes",
    "hiring manager coach",
    "generate role-specific interview questions with evaluation rubrics",
    [
      "Behavioral questions (5) with STAR evaluation criteria",
      "Technical or skills-based questions (3–5)",
      "Culture fit questions (2–3)",
      "Scorecard template for interviewers",
    ],
  ),
  starterPrompt(
    "Performance Review Writer",
    "business",
    ["Performance Review", "HR", "Feedback"],
    2.99,
    "intermediate",
    "30 minutes",
    "HR business partner",
    "draft a balanced performance review with strengths, growth areas, and goals",
    [
      "Summary of performance period",
      "Strengths with specific examples",
      "Growth areas with actionable development steps",
      "Goals for next review period",
    ],
  ),
  starterPrompt(
    "Customer Feedback Analyzer",
    "business",
    ["Feedback", "Customer Voice", "Insights"],
    2.99,
    "intermediate",
    "45 minutes",
    "customer experience analyst",
    "analyze customer feedback and extract themes, sentiment, and action items",
    [
      "Top themes with frequency and sentiment",
      "Critical issues requiring immediate action",
      "Feature requests ranked by impact",
      "Recommended response or product changes",
    ],
  ),
  starterPrompt(
    "Retention Strategy Planner",
    "business",
    ["Retention", "Churn", "Customer Success"],
    2.99,
    "intermediate",
    "1 hour",
    "customer retention strategist",
    "design a retention program with lifecycle triggers and interventions",
    [
      "Churn risk indicators to monitor",
      "Lifecycle touchpoints (onboarding, activation, renewal)",
      "Retention offers and win-back campaigns",
      "Success metrics and targets",
    ],
  ),
  starterPrompt(
    "Vendor Comparison Matrix",
    "business",
    ["Vendor", "Procurement", "Comparison"],
    1.99,
    "beginner",
    "30 minutes",
    "procurement analyst",
    "compare vendors or tools and recommend the best fit",
    [
      "Evaluation criteria with weights",
      "Side-by-side comparison table",
      "Total cost of ownership estimate",
      "Recommendation with rationale",
    ],
  ),
  starterPrompt(
    "Business Name Brainstormer",
    "business",
    ["Naming", "Branding", "Startup"],
    1.99,
    "beginner",
    "20 minutes",
    "brand naming consultant",
    "brainstorm business names with taglines and domain availability tips",
    [
      "15–20 name options grouped by style (descriptive, invented, compound)",
      "Tagline for top 5 picks",
      "Domain and trademark considerations",
      "Top 3 recommendations with rationale",
    ],
  ),
  starterPrompt(
    "Elevator Pitch Crafter",
    "business",
    ["Pitch", "Networking", "Storytelling"],
    1.99,
    "beginner",
    "15 minutes",
    "pitch coach",
    "craft a 30-second and 60-second elevator pitch",
    [
      "30-second pitch (problem, solution, traction/ask)",
      "60-second expanded version with proof points",
      "Hook opening line variants (3)",
      "Common objections and one-line responses",
    ],
  ),
  starterPrompt(
    "Partnership Outreach Email",
    "business",
    ["Partnership", "Outreach", "Collaboration"],
    2.99,
    "intermediate",
    "30 minutes",
    "partnerships manager",
    "write a partnership outreach email proposing mutual value",
    [
      "Subject line and personalized opening",
      "Partnership value proposition for both parties",
      "Specific collaboration ideas",
      "Low-friction next step CTA",
    ],
  ),
  starterPrompt(
    "Quarterly Business Review",
    "business",
    ["QBR", "Review", "Leadership"],
    2.99,
    "intermediate",
    "1 hour",
    "business operations lead",
    "prepare a quarterly business review deck outline with metrics and priorities",
    [
      "Executive summary of quarter performance",
      "KPI scorecard vs. targets",
      "Wins, misses, and root causes",
      "Priorities and resource asks for next quarter",
    ],
  ),

  // ── Marketing (20) ─────────────────────────────────────────────────
  starterPrompt(
    "Instagram Caption Writer",
    "marketing",
    ["Instagram", "Captions", "Social Media"],
    1.99,
    "beginner",
    "15 minutes",
    "Instagram copywriter",
    "write engaging Instagram captions with hooks, body copy, and hashtags",
    [
      "3 caption variants with different hooks",
      "Hashtag sets (broad reach + niche)",
      "CTA options",
      "Carousel slide suggestions if applicable",
    ],
  ),
  starterPrompt(
    "LinkedIn Post Generator",
    "marketing",
    ["LinkedIn", "B2B", "Thought Leadership"],
    1.99,
    "beginner",
    "20 minutes",
    "LinkedIn ghostwriter",
    "write authority-building LinkedIn posts with story hooks and professional CTAs",
    [
      "Hook line (first 2 lines optimized for 'see more')",
      "Post body with line breaks for readability",
      "Closing CTA or question for engagement",
      "2 alternate hook variants",
    ],
  ),
  starterPrompt(
    "Ad Headline Generator",
    "marketing",
    ["Headlines", "Ads", "Copy"],
    1.99,
    "beginner",
    "15 minutes",
    "direct response copywriter",
    "generate high-converting ad headline variants for search, social, or display",
    [
      "10 headline options grouped by angle (benefit, curiosity, urgency, social proof)",
      "Character count for each (platform-specific if provided)",
      "Recommended A/B test pairs",
      "Primary text companion lines (3)",
    ],
  ),
  starterPrompt(
    "Email Subject Line Writer",
    "marketing",
    ["Email", "Subject Lines", "Open Rate"],
    1.99,
    "beginner",
    "10 minutes",
    "email marketing copywriter",
    "write email subject lines optimized for open rates",
    [
      "10 subject line options under 50 characters",
      "Preview text suggestions (3)",
      "A/B test recommendations",
      "Spam-trigger words to avoid for this send",
    ],
  ),
  starterPrompt(
    "Product Description Writer",
    "marketing",
    ["E-commerce", "Product Copy", "Conversion"],
    1.99,
    "beginner",
    "20 minutes",
    "e-commerce copywriter",
    "write persuasive product descriptions with benefits, features, and SEO keywords",
    [
      "Short description (1–2 sentences for listings)",
      "Long description with benefit-led bullets",
      "Feature/spec table",
      "Suggested SEO keywords",
    ],
  ),
  starterPrompt(
    "Landing Page Hero Copy",
    "marketing",
    ["Landing Page", "Hero", "Conversion"],
    2.99,
    "intermediate",
    "30 minutes",
    "conversion copywriter",
    "write hero section copy for a landing page",
    [
      "Headline and subheadline variants (3 each)",
      "Primary and secondary CTA button text",
      "Trust indicators to display (social proof, guarantees)",
      "Above-the-fold copy block (full paragraph)",
    ],
  ),
  starterPrompt(
    "Facebook Ad Copy",
    "marketing",
    ["Facebook", "Paid Ads", "Social"],
    2.99,
    "intermediate",
    "30 minutes",
    "Facebook ads specialist",
    "create Facebook ad copy with primary text, headlines, and creative angles",
    [
      "3 ad variants with different angles (pain, aspiration, social proof)",
      "Primary text, headline, and description for each",
      "Creative brief notes (image/video suggestions)",
      "Audience targeting recommendations",
    ],
  ),
  starterPrompt(
    "Google Ads RSA Generator",
    "marketing",
    ["Google Ads", "RSA", "PPC"],
    2.99,
    "intermediate",
    "45 minutes",
    "Google Ads specialist",
    "generate Responsive Search Ad headlines and descriptions",
    [
      "15 headlines (30 char max) grouped by theme",
      "4 descriptions (90 char max)",
      "Suggested pin strategy",
      "Keyword themes to include in ad groups",
    ],
  ),
  starterPrompt(
    "Customer Persona Builder",
    "marketing",
    ["Persona", "ICP", "Audience"],
    2.99,
    "intermediate",
    "45 minutes",
    "market researcher",
    "build detailed customer personas with demographics, pain points, and buying triggers",
    [
      "1–3 persona profiles with name, role, and demographics",
      "Goals, frustrations, and objections",
      "Preferred channels and content types",
      "Messaging angles that resonate",
    ],
  ),
  starterPrompt(
    "Content Pillar Planner",
    "marketing",
    ["Content Strategy", "Pillars", "Planning"],
    2.99,
    "intermediate",
    "1 hour",
    "content strategist",
    "define content pillars and a 30-day content calendar",
    [
      "3–5 content pillars aligned to business goals",
      "Topic ideas per pillar (5 each)",
      "30-day calendar with formats and channels",
      "Repurposing plan across platforms",
    ],
  ),
  starterPrompt(
    "Viral Hook Generator",
    "marketing",
    ["Hooks", "Viral", "Short Form"],
    1.99,
    "beginner",
    "15 minutes",
    "short-form content specialist",
    "generate scroll-stopping hooks for reels, TikTok, and ads",
    [
      "20 hook options across formats (question, bold claim, story, statistic)",
      "Platform-specific recommendations",
      "Follow-up line suggestions for top 5 hooks",
      "Hooks to avoid for the user's niche",
    ],
  ),
  starterPrompt(
    "Hashtag Strategy Generator",
    "marketing",
    ["Hashtags", "Discovery", "Social Media"],
    1.99,
    "beginner",
    "10 minutes",
    "social media strategist",
    "create hashtag sets grouped by reach, niche, and campaign",
    [
      "Broad reach hashtags (10)",
      "Niche/community hashtags (10)",
      "Branded/campaign hashtags (3–5)",
      "Usage guidelines per platform",
    ],
  ),
  starterPrompt(
    "UGC Brief Creator",
    "marketing",
    ["UGC", "Creator Brief", "Influencer"],
    2.99,
    "intermediate",
    "30 minutes",
    "UGC campaign manager",
    "write a creator brief for user-generated content campaigns",
    [
      "Campaign objective and key message",
      "Do's and don'ts for creators",
      "Shot list and talking points",
      "Deliverables, timeline, and usage rights",
    ],
  ),
  starterPrompt(
    "Brand Voice Guidelines",
    "marketing",
    ["Brand Voice", "Tone", "Guidelines"],
    2.99,
    "intermediate",
    "45 minutes",
    "brand voice strategist",
    "define brand voice guidelines with tone pillars and examples",
    [
      "Voice attributes (3–5 with definitions)",
      "Tone spectrum (formal ↔ casual, serious ↔ playful)",
      "Do/don't word lists",
      "Sample copy rewrites in brand voice",
    ],
  ),
  starterPrompt(
    "Newsletter Edition Writer",
    "marketing",
    ["Newsletter", "Email", "Content"],
    2.99,
    "intermediate",
    "30 minutes",
    "newsletter editor",
    "write a complete newsletter edition with intro, sections, and CTA",
    [
      "Subject line and preview text",
      "Intro hook paragraph",
      "2–4 curated sections with summaries and links",
      "Closing CTA and sign-off",
    ],
  ),
  starterPrompt(
    "Case Study Outline",
    "marketing",
    ["Case Study", "Social Proof", "B2B"],
    2.99,
    "intermediate",
    "45 minutes",
    "B2B content marketer",
    "outline a customer case study with challenge, solution, and results",
    [
      "Customer background and challenge",
      "Solution implementation story",
      "Results with metrics (placeholders if TBD)",
      "Pull quotes and headline options",
    ],
  ),
  starterPrompt(
    "Referral Program Designer",
    "marketing",
    ["Referral", "Growth", "Word of Mouth"],
    2.99,
    "intermediate",
    "1 hour",
    "growth marketer",
    "design a referral program with incentives, mechanics, and promotion plan",
    [
      "Referrer and referee reward structure",
      "Program rules and eligibility",
      "Promotion channels and launch sequence",
      "Success metrics and tracking setup",
    ],
  ),
  starterPrompt(
    "Launch Email Sequence",
    "marketing",
    ["Launch", "Email Sequence", "Campaign"],
    2.99,
    "intermediate",
    "1 hour",
    "email launch strategist",
    "write a 5-email product launch sequence",
    [
      "Email 1: Teaser/announcement",
      "Email 2: Value/education",
      "Email 3: Social proof",
      "Email 4: Urgency/offer",
      "Email 5: Last chance + FAQ",
    ],
  ),
  starterPrompt(
    "TikTok Script Writer",
    "marketing",
    ["TikTok", "Script", "Short Form"],
    1.99,
    "beginner",
    "20 minutes",
    "TikTok scriptwriter",
    "write a TikTok video script with hook, body, and CTA",
    [
      "Hook (first 3 seconds) with on-screen text",
      "Script with timing beats (15s, 30s, or 60s)",
      "B-roll or visual suggestions",
      "Caption and hashtag recommendations",
    ],
  ),
  starterPrompt(
    "YouTube Title Optimizer",
    "marketing",
    ["YouTube", "Titles", "SEO"],
    1.99,
    "beginner",
    "15 minutes",
    "YouTube SEO specialist",
    "generate click-worthy YouTube titles optimized for search and CTR",
    [
      "10 title options with character counts",
      "Keyword placement recommendations",
      "Thumbnail text suggestions to pair with titles",
      "Titles to A/B test first",
    ],
  ),

  // ── Coding (10) ────────────────────────────────────────────────────
  starterPrompt(
    "Code Review Assistant",
    "coding",
    ["Code Review", "Quality", "Best Practices"],
    2.99,
    "intermediate",
    "30 minutes",
    "staff software engineer",
    "review code for bugs, security issues, performance, and style improvements",
    [
      "Critical issues (must fix)",
      "Suggestions (should fix)",
      "Nitpicks (optional)",
      "Refactoring recommendations with code examples",
    ],
  ),
  starterPrompt(
    "Bug Diagnosis Helper",
    "coding",
    ["Debugging", "Errors", "Troubleshooting"],
    2.99,
    "intermediate",
    "45 minutes",
    "senior debugger",
    "diagnose bugs from error messages, stack traces, and code snippets",
    [
      "Likely root cause(s) ranked by probability",
      "Steps to reproduce and verify",
      "Suggested fix with code",
      "Prevention recommendations",
    ],
  ),
  starterPrompt(
    "SQL Query Generator",
    "coding",
    ["SQL", "Database", "Queries"],
    1.99,
    "beginner",
    "20 minutes",
    "database engineer",
    "write optimized SQL queries from natural language requirements",
    [
      "SQL query with comments explaining logic",
      "Expected output description",
      "Index recommendations if performance matters",
      "Alternative query approaches if applicable",
    ],
  ),
  starterPrompt(
    "API Endpoint Designer",
    "coding",
    ["API", "REST", "Design"],
    2.99,
    "intermediate",
    "45 minutes",
    "API architect",
    "design REST API endpoints with request/response schemas",
    [
      "Endpoint list with HTTP methods and paths",
      "Request/response JSON schemas",
      "Error codes and messages",
      "Authentication and rate limiting notes",
    ],
  ),
  starterPrompt(
    "Unit Test Generator",
    "coding",
    ["Testing", "Unit Tests", "TDD"],
    1.99,
    "intermediate",
    "30 minutes",
    "test engineer",
    "write comprehensive unit tests for provided code",
    [
      "Test cases covering happy path, edge cases, and errors",
      "Test code in the user's framework (Jest, pytest, etc.)",
      "Mock/stub recommendations",
      "Coverage gaps to address",
    ],
  ),
  starterPrompt(
    "Regex Pattern Builder",
    "coding",
    ["Regex", "Pattern Matching", "Validation"],
    1.99,
    "beginner",
    "15 minutes",
    "regex specialist",
    "build regex patterns for validation, extraction, or replacement tasks",
    [
      "Regex pattern with explanation of each segment",
      "Test cases (match and non-match examples)",
      "Language-specific usage snippet",
      "Common pitfalls for this pattern",
    ],
  ),
  starterPrompt(
    "Git Commit Message Writer",
    "coding",
    ["Git", "Commits", "Conventions"],
    1.99,
    "beginner",
    "5 minutes",
    "open source maintainer",
    "write clear, conventional commit messages from a diff or change description",
    [
      "Commit subject line (50 char max, imperative mood)",
      "Commit body with what and why",
      "Breaking change footer if applicable",
      "Alternative subject lines (2)",
    ],
  ),
  starterPrompt(
    "README Generator",
    "coding",
    ["README", "Documentation", "Open Source"],
    1.99,
    "beginner",
    "30 minutes",
    "technical writer",
    "write a polished README for a software project",
    [
      "Project description and badges",
      "Installation and setup instructions",
      "Usage examples with code blocks",
      "Contributing and license sections",
    ],
  ),
  starterPrompt(
    "Refactoring Plan Writer",
    "coding",
    ["Refactoring", "Clean Code", "Architecture"],
    2.99,
    "advanced",
    "1 hour",
    "software refactoring specialist",
    "create a phased refactoring plan for legacy or messy code",
    [
      "Current pain points and technical debt inventory",
      "Phased refactoring steps with risk assessment",
      "Test coverage goals before each phase",
      "Estimated effort per phase",
    ],
  ),
  starterPrompt(
    "Error Message Explainer",
    "coding",
    ["Errors", "Debugging", "Learning"],
    1.99,
    "beginner",
    "15 minutes",
    "patient programming tutor",
    "explain error messages in plain language with fix steps",
    [
      "Plain-language explanation of the error",
      "Common causes ranked by likelihood",
      "Step-by-step fix instructions",
      "How to prevent this error in the future",
    ],
  ),

  // ── Finance (10) ───────────────────────────────────────────────────
  starterPrompt(
    "Monthly Budget Builder",
    "finance",
    ["Budget", "Personal Finance", "Planning"],
    1.99,
    "beginner",
    "30 minutes",
    "personal finance advisor",
    "create a monthly budget from income, expenses, and financial goals",
    [
      "Income vs. expense summary",
      "Recommended budget by category (50/30/20 or custom)",
      "Savings allocation",
      "3 actionable spending improvements",
    ],
  ),
  starterPrompt(
    "Debt Payoff Planner",
    "finance",
    ["Debt", "Payoff", "Snowball"],
    2.99,
    "intermediate",
    "45 minutes",
    "debt reduction coach",
    "create a debt payoff plan using avalanche or snowball method",
    [
      "Debt inventory with balances, rates, and minimums",
      "Payoff strategy comparison (avalanche vs. snowball)",
      "Monthly payment schedule with payoff dates",
      "Extra payment impact scenarios",
    ],
  ),
  starterPrompt(
    "Emergency Fund Calculator",
    "finance",
    ["Emergency Fund", "Savings", "Security"],
    1.99,
    "beginner",
    "20 minutes",
    "financial planner",
    "calculate emergency fund target and monthly savings plan",
    [
      "Recommended fund size (3–6 months expenses)",
      "Monthly savings amount to reach target",
      "Timeline to fully funded",
      "Where to keep the fund (HYSA, etc.)",
    ],
  ),
  starterPrompt(
    "Investment Portfolio Review",
    "finance",
    ["Investing", "Portfolio", "Allocation"],
    2.99,
    "intermediate",
    "1 hour",
    "investment advisor (educational, not financial advice)",
    "review portfolio allocation and suggest rebalancing considerations",
    [
      "Current allocation breakdown by asset class",
      "Risk profile assessment",
      "Rebalancing recommendations",
      "Questions to ask a licensed financial advisor",
      "Disclaimer that this is educational, not personalized financial advice",
    ],
    "Always include a disclaimer that this is general educational information, not licensed financial advice.",
  ),
  starterPrompt(
    "Side Income Tracker Setup",
    "finance",
    ["Side Income", "Freelance", "Tracking"],
    1.99,
    "beginner",
    "30 minutes",
    "freelance finance coach",
    "set up a side income tracking system with categories and tax prep",
    [
      "Income categories and tracking template",
      "Expense categories for deductions",
      "Estimated tax set-aside percentage",
      "Monthly review checklist",
    ],
  ),
  starterPrompt(
    "Tax Deduction Checklist",
    "finance",
    ["Taxes", "Deductions", "Freelance"],
    2.99,
    "intermediate",
    "45 minutes",
    "tax preparation assistant (educational)",
    "create a tax deduction checklist for the user's situation",
    [
      "Deduction categories relevant to user's work type",
      "Documentation needed for each",
      "Commonly missed deductions",
      "Reminder to consult a tax professional",
    ],
    "This is educational tax information, not professional tax advice. Always recommend consulting a CPA.",
  ),
  starterPrompt(
    "Freelance Rate Calculator",
    "finance",
    ["Freelance", "Pricing", "Rates"],
    2.99,
    "intermediate",
    "30 minutes",
    "freelance business coach",
    "calculate sustainable freelance hourly and project rates",
    [
      "Annual income goal breakdown",
      "Billable hours estimate after overhead",
      "Minimum hourly rate",
      "Project pricing formula with buffer",
    ],
  ),
  starterPrompt(
    "Expense Category Analyzer",
    "finance",
    ["Expenses", "Analysis", "Spending"],
    1.99,
    "beginner",
    "30 minutes",
    "spending analyst",
    "analyze expenses and identify savings opportunities",
    [
      "Spending breakdown by category with percentages",
      "Top 3 overspending areas",
      "Specific cut recommendations",
      "Realistic monthly savings target",
    ],
  ),
  starterPrompt(
    "Retirement Savings Planner",
    "finance",
    ["Retirement", "401k", "Long-term"],
    2.99,
    "intermediate",
    "45 minutes",
    "retirement planning educator",
    "estimate retirement savings needs and contribution targets",
    [
      "Retirement income goal estimate",
      "Current savings gap analysis",
      "Monthly contribution recommendation",
      "Account type suggestions (401k, IRA, etc.)",
    ],
    "Educational planning only — recommend consulting a financial advisor for personalized advice.",
  ),
  starterPrompt(
    "Cash Flow Forecaster",
    "finance",
    ["Cash Flow", "Forecast", "Business Finance"],
    2.99,
    "intermediate",
    "1 hour",
    "small business CFO advisor",
    "forecast cash flow for the next 3–6 months",
    [
      "Monthly cash in vs. cash out projection",
      "Runway calculation",
      "Cash crunch warning months",
      "Actions to improve cash position",
    ],
  ),

  // ── Writing (10) ─────────────────────────────────────────────────────
  starterPrompt(
    "Blog Post Outliner",
    "writing",
    ["Blog", "Outline", "SEO"],
    1.99,
    "beginner",
    "30 minutes",
    "content strategist",
    "create an SEO-friendly blog post outline with headings and key points",
    [
      "Working title and meta description",
      "H2/H3 outline with bullet points per section",
      "Target keywords and placement notes",
      "Internal/external link suggestions",
    ],
  ),
  starterPrompt(
    "Email Rewriter Pro",
    "writing",
    ["Email", "Professional", "Tone"],
    1.99,
    "beginner",
    "10 minutes",
    "professional editor",
    "rewrite emails for clarity, tone, and impact while preserving intent",
    [
      "Rewritten email in requested tone",
      "Subject line improvement",
      "Brief notes on key changes",
      "Alternative shorter version if applicable",
    ],
  ),
  starterPrompt(
    "Resume Bullet Improver",
    "writing",
    ["Resume", "Career", "ATS"],
    1.99,
    "beginner",
    "20 minutes",
    "resume coach",
    "transform weak resume bullets into achievement-driven statements",
    [
      "Rewritten bullets with action verbs and metrics",
      "Before/after comparison",
      "ATS keyword suggestions",
      "Tips for quantifying impact",
    ],
  ),
  starterPrompt(
    "Cover Letter Generator",
    "writing",
    ["Cover Letter", "Job Search", "Applications"],
    1.99,
    "beginner",
    "20 minutes",
    "career coach",
    "draft a tailored cover letter connecting experience to the target role",
    [
      "Opening hook tied to company/role",
      "Body paragraphs mapping skills to requirements",
      "Closing with clear CTA",
      "Word count and tone check",
    ],
  ),
  starterPrompt(
    "Professional Bio Writer",
    "writing",
    ["Bio", "Personal Brand", "About"],
    1.99,
    "beginner",
    "15 minutes",
    "personal branding writer",
    "write professional bios for website, LinkedIn, or speaker pages",
    [
      "Short bio (50 words)",
      "Medium bio (100 words)",
      "Long bio (200 words)",
      "First-person and third-person versions",
    ],
  ),
  starterPrompt(
    "Speech Outline Creator",
    "writing",
    ["Speech", "Public Speaking", "Presentation"],
    2.99,
    "intermediate",
    "45 minutes",
    "speechwriter",
    "outline a speech with opening hook, narrative structure, and closing",
    [
      "Speech objective and audience analysis",
      "Section-by-section outline with timing",
      "Opening hook options (3)",
      "Memorable closing and call to action",
    ],
  ),
  starterPrompt(
    "Press Release Drafter",
    "writing",
    ["Press Release", "PR", "Media"],
    2.99,
    "intermediate",
    "30 minutes",
    "PR writer",
    "draft a newsworthy press release in AP style",
    [
      "Headline and subheadline",
      "Lead paragraph (who, what, when, where, why)",
      "Body with quotes and supporting details",
      "Boilerplate and media contact info placeholder",
    ],
  ),
  starterPrompt(
    "Product Review Writer",
    "writing",
    ["Reviews", "Affiliate", "Content"],
    1.99,
    "beginner",
    "30 minutes",
    "product review writer",
    "write an honest, structured product review",
    [
      "Summary verdict and rating rationale",
      "Pros and cons list",
      "Feature-by-feature analysis",
      "Who should (and shouldn't) buy",
    ],
  ),
  starterPrompt(
    "Story Opening Hook",
    "writing",
    ["Fiction", "Creative Writing", "Hook"],
    1.99,
    "beginner",
    "20 minutes",
    "fiction writing coach",
    "craft compelling opening hooks for stories or novels",
    [
      "5 opening line options across styles (action, mystery, voice, setting, dialogue)",
      "Suggested next paragraph for top pick",
      "Genre-specific notes",
      "Hooks to avoid for this story type",
    ],
  ),
  starterPrompt(
    "FAQ Page Generator",
    "writing",
    ["FAQ", "Support", "Documentation"],
    1.99,
    "beginner",
    "30 minutes",
    "technical content writer",
    "generate a comprehensive FAQ page organized by topic",
    [
      "FAQ categories with 3–5 questions each",
      "Clear, concise answers",
      "Cross-links between related questions",
      "Suggested order for page layout",
    ],
  ),

  // ── Education (10) ─────────────────────────────────────────────────
  starterPrompt(
    "Lesson Plan Builder",
    "education",
    ["Lesson Plan", "Teaching", "Curriculum"],
    1.99,
    "beginner",
    "45 minutes",
    "instructional designer",
    "create a complete lesson plan with objectives, activities, and assessment",
    [
      "Learning objectives (measurable)",
      "Warm-up, instruction, practice, and closure activities with timing",
      "Materials needed",
      "Formative assessment and differentiation notes",
    ],
  ),
  starterPrompt(
    "Quiz Question Generator",
    "education",
    ["Quiz", "Assessment", "Questions"],
    1.99,
    "beginner",
    "30 minutes",
    "assessment designer",
    "generate quiz questions with answer keys for a given topic",
    [
      "10–15 questions mixed format (MC, short answer, true/false)",
      "Answer key with explanations",
      "Difficulty distribution (easy/medium/hard)",
      "Suggested point values",
    ],
  ),
  starterPrompt(
    "Study Guide Creator",
    "education",
    ["Study Guide", "Review", "Students"],
    1.99,
    "beginner",
    "30 minutes",
    "academic tutor",
    "create a study guide for an upcoming exam or unit",
    [
      "Key concepts summary",
      "Important terms and definitions",
      "Practice questions with answers",
      "Study schedule for exam prep",
    ],
  ),
  starterPrompt(
    "Rubric Designer",
    "education",
    ["Rubric", "Grading", "Assessment"],
    2.99,
    "intermediate",
    "30 minutes",
    "assessment specialist",
    "design a grading rubric with criteria and performance levels",
    [
      "3–5 grading criteria",
      "4 performance levels per criterion (e.g., exemplary to beginning)",
      "Descriptor text for each cell",
      "Total points and weighting",
    ],
  ),
  starterPrompt(
    "Parent Communication Email",
    "education",
    ["Parent Communication", "Email", "Classroom"],
    1.99,
    "beginner",
    "15 minutes",
    "teacher communication specialist",
    "write professional emails to parents about classroom updates or concerns",
    [
      "Subject line",
      "Email body with clear, warm tone",
      "Action items for parents if any",
      "Alternative shorter version for SMS/app notification",
    ],
  ),
  starterPrompt(
    "Differentiated Instruction Planner",
    "education",
    ["Differentiation", "Inclusion", "UDL"],
    2.99,
    "intermediate",
    "45 minutes",
    "special education consultant",
    "plan differentiated activities for diverse learners in one lesson",
    [
      "Lesson core objective",
      "Tier 1 (on-level), Tier 2 (support), Tier 3 (extension) activities",
      "Accommodations for specific needs mentioned",
      "Assessment adjustments",
    ],
  ),
  starterPrompt(
    "Classroom Activity Designer",
    "education",
    ["Activities", "Engagement", "Interactive"],
    1.99,
    "beginner",
    "30 minutes",
    "engagement-focused teacher coach",
    "design an interactive classroom activity for a specific topic",
    [
      "Activity overview and learning goal",
      "Step-by-step facilitation guide with timing",
      "Materials and setup",
      "Debrief questions and variations",
    ],
  ),
  starterPrompt(
    "Research Paper Outliner",
    "education",
    ["Research Paper", "Academic Writing", "Outline"],
    2.99,
    "intermediate",
    "45 minutes",
    "academic writing tutor",
    "outline a research paper with thesis, sections, and source integration plan",
    [
      "Thesis statement options (2–3)",
      "Section outline with argument flow",
      "Suggested source types and integration points",
      "Citation format reminders",
    ],
  ),
  starterPrompt(
    "Course Syllabus Writer",
    "education",
    ["Syllabus", "Course Design", "Higher Ed"],
    2.99,
    "intermediate",
    "1 hour",
    "curriculum designer",
    "write a complete course syllabus with policies, schedule, and outcomes",
    [
      "Course description and learning outcomes",
      "Weekly schedule with topics and assignments",
      "Grading breakdown and policies",
      "Required materials and communication expectations",
    ],
  ),
  starterPrompt(
    "Student Feedback Generator",
    "education",
    ["Feedback", "Grading", "Comments"],
    1.99,
    "beginner",
    "20 minutes",
    "formative assessment coach",
    "write constructive, specific feedback on student work",
    [
      "Strengths highlighted with examples from the work",
      "Areas for improvement with actionable suggestions",
      "Encouraging closing note",
      "Next steps or resources",
    ],
  ),
];
